### PR TITLE
Hackerrank problems

### PR DESCRIPTION
**Pull request by Mjamal-ubuntu**
This branch is developing a C++ problems from Hacker rank site to practicing.

### CODE REVIEW

**Review by gemy-97 — CHANGES_REQUESTED** [review]
I think this branch need to be rebased in the latest origin/master commit , not basing on other branch

**Comment by gemy-97** [comment]
I think also the hacker rank folder will need to be modified as changes for the structure of the folder. 
The another PR will submit the change for the beginning structure of the folder, and any updates in the folder structure will need to be with the change commit.

**Comment by Mjamal-ubuntu** [comment]
the branch rebased , done

**Comment by gemy-97** [comment]
looks fine to me

**Review by gemy-97 — APPROVED** [review]

**Pull request merged**
